version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061051227245.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t mycustomnginx:latest .
      - docker tag mycustomnginx:latest 061051227245.dkr.ecr.us-east-1.amazonaws.com/mycustomnginx:latest
  post_build:
    commands:
      - docker push 061051227245.dkr.ecr.us-east-1.amazonaws.com/mycustomnginx:latest
      - printf '[{"name":"mynode","imageUri":"%s"}]' mycustomnginx > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
